name: CI/CD Pipeline for SpaceX Viewer

on:
  push:
    branches: [ main ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ || true

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t spacex-viewer .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name spacex-test spacex-viewer

    - name: Test app is running in container
      run: |
        sleep 5
        curl --fail http://localhost:5000

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}
        docker tag spacex-viewer $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
